"""
Note: This code was generated by ChatGPT.
"""

import tkinter as tk
from tkinter import simpledialog, messagebox

CELL_SIZE = 40
COLORS = {
    0: "white",
    1: "#00ccff",
    2: "#00ff00",
    3: "#ff9900",
    4: "#ff0000",
    5: "#9900ff",
    6: "#ff00ff",
    7: "#ffff00",
    8: "#999999",
    9: "#006600",
    10: "#000000"
}

class GridPainter:
    def __init__(self, root, rows=8, cols=14):
        self.root = root
        self.rows = rows
        self.cols = cols
        self.cell_size = CELL_SIZE
        self.current_value = 1
        self.grid = [[0 for _ in range(cols)] for _ in range(rows)]

        # UI
        self.canvas = tk.Canvas(root)
        self.canvas.pack()
        self.canvas.bind("<Button-1>", self.paint_cell)
        self.canvas.bind("<B1-Motion>", self.paint_cell)

        self.value_label = tk.Label(root, text=f"Current Value: {self.current_value}")
        self.value_label.pack()

        tk.Button(root, text="Change Value", command=self.change_value).pack(pady=2)
        tk.Button(root, text="Resize Grid", command=self.resize_grid_dialog).pack(pady=2)
        tk.Button(root, text="Copy Export to Clipboard", command=self.export_to_clipboard).pack(pady=2)

        self.rects = []
        self.draw_grid()

    # --- Grid Functions ---
    def draw_grid(self):
        self.canvas.delete("all")
        self.rects = [[None for _ in range(self.cols)] for _ in range(self.rows)]
        self.canvas.config(width=self.cols * self.cell_size, height=self.rows * self.cell_size)
        for r in range(self.rows):
            for c in range(self.cols):
                x1, y1 = c * self.cell_size, r * self.cell_size
                x2, y2 = x1 + self.cell_size, y1 + self.cell_size
                color = COLORS[self.grid[r][c]]
                self.rects[r][c] = self.canvas.create_rectangle(
                    x1, y1, x2, y2, fill=color, outline="black"
                )

    def paint_cell(self, event):
        c = event.x // self.cell_size
        r = event.y // self.cell_size
        if 0 <= r < self.rows and 0 <= c < self.cols:
            self.grid[r][c] = self.current_value
            self.canvas.itemconfig(self.rects[r][c], fill=COLORS[self.current_value])

    def change_value(self):
        val = simpledialog.askinteger("Value", "Enter value (0–10):", minvalue=0, maxvalue=10)
        if val is not None:
            self.current_value = val
            self.value_label.config(text=f"Current Value: {self.current_value}")

    def resize_grid_dialog(self):
        new_rows = simpledialog.askinteger("Resize", "Number of rows:", minvalue=1, maxvalue=100)
        new_cols = simpledialog.askinteger("Resize", "Number of columns:", minvalue=1, maxvalue=100)
        if new_rows and new_cols:
            self.resize_grid(new_rows, new_cols)

    def resize_grid(self, new_rows, new_cols):
        new_grid = [[0 for _ in range(new_cols)] for _ in range(new_rows)]
        # preserve overlapping cells
        for r in range(min(self.rows, new_rows)):
            for c in range(min(self.cols, new_cols)):
                new_grid[r][c] = self.grid[r][c]
        self.rows, self.cols, self.grid = new_rows, new_cols, new_grid
        self.draw_grid()

    # --- Export ---
    def export_to_clipboard(self):
        text = "{\n"
        for row in self.grid:
            text += "   " + ", ".join(str(v) for v in row) + ",\n"
        text += "};"

        self.root.clipboard_clear()
        self.root.clipboard_append(text)
        self.root.update()
        messagebox.showinfo("Copied!", "Grid copied to clipboard.")

if __name__ == "__main__":
    root = tk.Tk()
    root.title("Dynamic Grid Painter")
    app = GridPainter(root)
    root.mainloop()